[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-vercel-app.vercel.app"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-vercel-app.vercel.app"
